version: '3'

services:
  dc-python:
    image: dc-python
    build:
        context: ./DataCollector
    volumes:
      - ./nginx/content/tiff:/static_content/tiff:z
      - ./nginx/content/images:/static_content/images:z
    links:
      - influxdb
    entrypoint: 
      - 'python'
      - 'run_dc.py'
    ports:
      - "8080:8080"  

  dc-nginx:
    image: dc-nginx
    build:
        context: ./nginx
    volumes:
      - ./nginx/log:/var/log/nginx/log:Z
      - ./nginx/content/tiff:/static/tiff:z
      - ./nginx/content/images:/static/images:z
    links:
      - chronograf
    entrypoint:
      - 'nginx'
      - '-g'
      - 'daemon off;'
    ports:
      - "80:80"
      - "443:443"

  influxdb:
    image: influxdb:1.3.5
    volumes:
        - ./tick-stack/data/influxdb:/var/lib/influxdb:Z
    ports:
      - "8086:8086"
  # Define a Chronograf service

  chronograf:
    image: chronograf:1.3.8
    environment:
      # BASE_PATH: /chronograf
      INFLUXDB_URL: http://influxdb:8086
      # KAPACITOR_URL: http://kapacitor:9092
    ports:
      - "8888:8888"
    links:
      - influxdb
