version: '3'

services:
  dc-python:
    image: dc-python
    volumes:
      - ./DataCollector:/src/DataCollector
    links:
      - influxdb
    ports:
      - "8080:8080"  

  dc-nginx:
    image: dc-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/log:/var/log/nginx/log:rw
    links:
        - chronograf
    ports:
      - "80:80/tcp"
      - "443:443/tcp"

  telegraf:
    image: telegraf:1.4.0
    volumes:
      - ./tick-stack/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    links:
      - influxdb
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
  # Define an InfluxDB service

  influxdb:
    image: influxdb:1.3.5
    volumes:
      - ./tick-stack/data/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
  # Define a Chronograf service

  chronograf:
    image: chronograf:1.3.8
    environment:
      INFLUXDB_URL: http://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
    ports:
      - "8888:8888"
    links:
      - influxdb
      - kapacitor
  # Define a Kapacitor service

  kapacitor:
    image: kapacitor:1.3.3
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    links:
      - influxdb
    ports:
      - "9092:9092"
